package org.itc.integracion.services.sifi.servicioactualizarclientesafe.v1.fachada;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.itc.integracion.services.sifi.servicioactualizarclientesafe.v1.ServicioActualizarStateSafe;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "ServicioActualizarClienteSafeFachadaWSService",
                  wsdlLocation = "classpath:wsdl/ServicioSifiUpdateSafe.wsdl",
                  targetNamespace = "http://fachada.v1.servicioactualizarclientesafe.sifi.services.integracion.org.itc/")
public class ServicioActualizarClienteSafeFachadaWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fachada.v1.servicioactualizarclientesafe.sifi.services.integracion.org.itc/", "ServicioActualizarClienteSafeFachadaWSService");
    public final static QName ServicioActualizarClienteSafeFachadaWSPort = new QName("http://fachada.v1.servicioactualizarclientesafe.sifi.services.integracion.org.itc/", "ServicioActualizarClienteSafeFachadaWSPort");
    static {
        URL url = ServicioActualizarClienteSafeFachadaWSService.class.getClassLoader().getResource("wsdl/ServicioSifiUpdateSafe.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServicioActualizarClienteSafeFachadaWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/ServicioSifiUpdateSafe.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioActualizarClienteSafeFachadaWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioActualizarClienteSafeFachadaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioActualizarClienteSafeFachadaWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioActualizarClienteSafeFachadaWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioActualizarClienteSafeFachadaWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioActualizarClienteSafeFachadaWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicioActualizarStateSafe
     */
    @WebEndpoint(name = "ServicioActualizarClienteSafeFachadaWSPort")
    public ServicioActualizarStateSafe getServicioActualizarClienteSafeFachadaWSPort() {
        return super.getPort(ServicioActualizarClienteSafeFachadaWSPort, ServicioActualizarStateSafe.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioActualizarStateSafe
     */
    @WebEndpoint(name = "ServicioActualizarClienteSafeFachadaWSPort")
    public ServicioActualizarStateSafe getServicioActualizarClienteSafeFachadaWSPort(WebServiceFeature... features) {
        return super.getPort(ServicioActualizarClienteSafeFachadaWSPort, ServicioActualizarStateSafe.class, features);
    }

}
