package org.itc.integracion.services.sifi.servicioactualizarclientesafe.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * Generated source version: 3.2.5
 *
 */
/*
@WebService(targetNamespace = "http://org.itc/integracion/services/sifi/ServicioSincronizarCliente/V1", name = "ServicioSincronizarCliente")
@XmlSeeAlso({org.itc.integracion.sifi.canal.common.aggregate.component.ObjectFactory.class, org.itc.integracion.sifi.common.basic.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Policy(uri = "classpath:ws-securitypolicies/UsernameTokenWithPasswordDigestOverHTTP.xml", includeInWSDL = true, placement = Policy.Placement.DEFAULT)
*/

@WebService(targetNamespace = "http://org.itc/integracion/services/sifi/ServicioActualizarClienteSafe/V1", name = "ServicioActualizarStateSafe")
@XmlSeeAlso({org.itc.salesforce.sifi.xsd.commonbasiccomponents_2_1.ObjectFactory.class, org.itc.salesforce.sifi.schema.xsd.commonaggregatecomponents_2_1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicioActualizarStateSafe {

    @WebMethod(action = "http://org.itc/integracion/services/sifi/ServicioActualizarClienteSafe/V1/crm")
    @WebResult(name = "actualizarCrmSifiSafeResponse", targetNamespace = "org:itc:salesforce:sifi:schema:xsd:CommonAggregateComponents-2-1", partName = "actualizarStateCrmSifiResponse")
    public org.itc.salesforce.sifi.schema.xsd.commonaggregatecomponents_2_1.ResposeServiceType actualizarStateCrmSifi(
        @WebParam(partName = "actualizarStateCrmSifiRequest", name = "actualizarCrmSifiSafeRequest", targetNamespace = "org:itc:salesforce:sifi:schema:xsd:CommonAggregateComponents-2-1")
        org.itc.salesforce.sifi.schema.xsd.commonaggregatecomponents_2_1.ActualizarCrmSifiSafeRequestType actualizarStateCrmSifiRequest
    ) throws ActualizarStateCrmSifiFault;
}
