package org.adarchitecture.ws.services.user.serviciosincronizarcliente.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "ServicioSincronizarCliente",
                  wsdlLocation = "classpath:wsdl/ServicioSincronizarCliente.wsdl",
                  targetNamespace = "http://org.adarchitecture/services/user/ServicioSincronizarCliente/V1")
public class ServicioSincronizarCliente_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://org.adarchitecture/services/user/ServicioSincronizarCliente/V1", "ServicioSincronizarCliente");
    public final static QName ServicioSincronizarClienteSOAP = new QName("http://org.adarchitecture/services/user/ServicioSincronizarCliente/V1", "ServicioSincronizarClienteSOAP");
    static {
        URL url = ServicioSincronizarCliente_Service.class.getClassLoader().getResource("wsdl/ServicioSincronizarCliente.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServicioSincronizarCliente_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/ServicioSincronizarCliente.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioSincronizarCliente_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioSincronizarCliente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSincronizarCliente_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioSincronizarCliente_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioSincronizarCliente_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioSincronizarCliente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicioSincronizarCliente
     */
    @WebEndpoint(name = "ServicioSincronizarClienteSOAP")
    public ServicioSincronizarCliente getServicioSincronizarClienteSOAP() {
        return super.getPort(ServicioSincronizarClienteSOAP, ServicioSincronizarCliente.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSincronizarCliente
     */
    @WebEndpoint(name = "ServicioSincronizarClienteSOAP")
    public ServicioSincronizarCliente getServicioSincronizarClienteSOAP(WebServiceFeature... features) {
        return super.getPort(ServicioSincronizarClienteSOAP, ServicioSincronizarCliente.class, features);
    }

}
