package org.adarchitecture.ws.services.user.serviciosincronizarcliente.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

//import org.apache.cxf.annotations.Policy;

/**
 * This class was generated by Apache CXF 3.2.5
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://org.adarchitecture/services/user/ServicioSincronizarCliente/V1", name = "ServicioSincronizarCliente")
@XmlSeeAlso({org.adarchitecture.ws.user.canal.common.aggregate.component.ObjectFactory.class, org.adarchitecture.ws.user.common.basic.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//@Policy(uri = "classpath:ws-securitypolicies/UsernameToken-PasswordText-HTTP-Policy.xml", includeInWSDL = true, placement = Policy.Placement.DEFAULT)
public interface ServicioSincronizarCliente {

    @WebMethod(action = "http://org.adarchitecture/services/user/ServicioSincronizarCliente/V1/sincronizarCrmUser")
    @WebResult(name = "sincronizarCrmUserResponse", targetNamespace = "org:adarchitecture:salesforce:user:schema:xsd:CommonAggregateComponents-2", partName = "sincronizarCrmUserSafesResponse")
    public org.adarchitecture.ws.user.canal.common.aggregate.component.ResposeServiceType sincronizarCrmUser(
        @WebParam(partName = "sincronizarCrmUserSafesRequest", name = "sincronizarCrmUserRequest", targetNamespace = "org:adarchitecture:salesforce:user:schema:xsd:CommonAggregateComponents-2")
        org.adarchitecture.ws.user.canal.common.aggregate.component.SincronizarCrmUserRequestType sincronizarCrmUserSafesRequest
    ) throws SincronizarCrmUserFault;
}
